// <auto-generated />
namespace TurboRango.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Criar_tabela_prato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criar_tabela_prato));
        
        string IMigrationMetadata.Id
        {
            get { return "201506120025303_Criar_tabela_prato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
